---
# Whether to attempt downloading the RPM directly from the NetApp SF Artifactory server
from_artifactory: "{{ from_artifactory | default(True) }}"
sf_auto_install_rpm: True
sf_rpm_from_artifactory: False
sf_configure_test_cluster: False
